BACKEND_STATUS_TOOL = "get_backend_status"
CLUSTER_OVERVIEW_TOOL = "get_cluster_overview"
SERVICE_TRIAGE_METRICS_TOOL = "get_service_triage_metrics"
POD_TRIAGE_METRICS_TOOL = "get_pod_triage_metrics"
SUMMARIZE_SERVICE_LOGS_TOOL = "summarize_service_logs"
SUMMARIZE_POD_LOGS_TOOL = "summarize_pod_logs"

DETECTION_LITE_TOOLS = [
    BACKEND_STATUS_TOOL,
    CLUSTER_OVERVIEW_TOOL,
    SERVICE_TRIAGE_METRICS_TOOL,
    POD_TRIAGE_METRICS_TOOL,
    SUMMARIZE_SERVICE_LOGS_TOOL,
    SUMMARIZE_POD_LOGS_TOOL,
]