GET_PODS_FROM_SERVICE_TOOL = "get_pods_from_service"
GET_SERVICES_FROM_POD_TOOL = "get_services_from_pod"
SUMMARIZE_SERVICE_LOGS_TOOL = "summarize_service_logs"
SUMMARIZE_POD_LOGS_TOOL = "summarize_pod_logs"
GET_SERVICE_METRICS_TOOL = "get_service_metrics"
GET_POD_METRICS_TOOL = "get_pod_metrics"
GET_SERVICE_TRIAGE_METRICS_TOOL = "get_service_triage_metrics"
GET_POD_TRIAGE_METRICS_TOOL = "get_pod_triage_metrics"
GET_TRACE_SUMMARIES_TOOL = "get_trace_summaries"
GET_TRACE_DETAILS_TOOL = "get_trace_details"
GET_SERVICE_DEPENDENCIES_TOOL = "get_service_dependencies"
GET_SERVICES_USED_BY_TOOL = "get_services_used_by"
GET_SERVICE_MAP_TOOL = "get_service_map"
EXEC_KUBECTL_TOOL = "exec_kubectl"
EXEC_SHELL_TOOL = "exec_shell"

DIAGNOSIS_TOOLS = [
    GET_PODS_FROM_SERVICE_TOOL,
    GET_SERVICES_FROM_POD_TOOL,
    SUMMARIZE_SERVICE_LOGS_TOOL,
    SUMMARIZE_POD_LOGS_TOOL,
    GET_SERVICE_METRICS_TOOL,
    GET_POD_METRICS_TOOL,
    GET_SERVICE_TRIAGE_METRICS_TOOL,
    GET_POD_TRIAGE_METRICS_TOOL,
    GET_TRACE_SUMMARIES_TOOL,
    GET_TRACE_DETAILS_TOOL,
    GET_SERVICE_DEPENDENCIES_TOOL,
    GET_SERVICES_USED_BY_TOOL,
    GET_SERVICE_MAP_TOOL,
    EXEC_KUBECTL_TOOL,
    EXEC_SHELL_TOOL,
]