GET_SERVICE_TOPOLOGY_SUMMARY_TOOL = "get_service_topology_summary"
GET_BACKEND_STATUS_TOOL = "get_backend_status"

SUPERVISOR_TOOLS = [
    GET_SERVICE_TOPOLOGY_SUMMARY_TOOL,
    GET_BACKEND_STATUS_TOOL,
]